#NumPy exercises
Authors:  Natanael Moura Junior (natanael.junior@mjv.com.br) <br>
          Carlos Eduardo Covas Costa (carlos.costa@mjv.com.br)


<img align="center" width="200" src="https://raw.githubusercontent.com/natmourajr/data/main/mjv-tecnologia.png?raw=1">

**Question 1** -  Import the NumPy library and assign the *np* allias to it.

In [1]:
import numpy as np

**Question 2** - Create a 1D array with 10 elements (from 1 to 12) by using a list of integers.

In [ ]:
X = np.array([1,2,3,4,5,6,7,8,9,10])
print(X.shape)

(10,)


**Question 3** - Create a matrix (2D array) using a built-in function. This matrix has the following characteristics: 4 rows, 3 columns and it is populated with consecutive integers from 1 to 12(including).

In [ ]:
X = np.arange(1,13).reshape(4,3)
print(X.shape)
print(X)

(4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**Question 4** - Create a 4x4 ndarray by using a Built-in function that only contains consecutive even numbers from 2 to 32 (inclusive).

In [ ]:
X = np.arange(2,33,2)  #must make range upper 33 to include 32, similar to indexing
print(X)
new_X = X.reshape(4, 4)
print(new_X)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


**Question 5** - reate a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive). Afterwards use Boolean indexing to pick out only the odd numbers in the array.

In [ ]:
X = np.arange(1, 26).reshape(5, 5)
print(X)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
#Type your code here
# Use Boolean indexing to pick out only the odd numbers in the array
boolean = (X % 2) != 0
print(boolean)
X = X[boolean]
print(X)

[[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


**Question 6** - Create a 5x5 ndarray with consecutive integers from 1 to 25 (inclusive). Then, slice this 5x5 ndarray from 2nd to 3rd rows and from 2nd to last column (including) to create a new ndarray.

In [ ]:
#Type your code here
# create the 5x5 ndarray

X = np.arange(1, 26).reshape(5, 5)
print(X)
#slice
print(X[1:3, 1:])



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 7  8  9 10]
 [12 13 14 15]]


In [ ]:
#Type your code here
#create the new ndarray from X using the slice from 7th position to 15th position (including).
new_X= X.reshape(-1)
print(new_X)
#slice
print(new_X[6:15])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[ 7  8  9 10 11 12 13 14 15]


**Question 7** - Create a 1D ndarray with 10 zeros and 2x5 ndarray with zeros.

In [ ]:
#Type your code here
#1D ndarray with 10 zeros
print(np.zeros((1,10), dtype = np.int))

[[0 0 0 0 0 0 0 0 0 0]]


In [ ]:
#Type your code here
#2x5 ndarray of zeros
print(np.zeros((2,5), dtype = np.int))

[[0 0 0 0 0]
 [0 0 0 0 0]]


**Question 8** - Create a 5x5 ndarray of random numbers and subtract each element by 1.

**Comment**: Good job! Once we use numpy structure, you could just subtract 1 from the matrix, so numpy will apply it to each matrix element. Thus, you don't need to create a matrix of ones that will save memory. For example, the code can be like this:

In [5]:
X = np.random.randint(1,13,(5,5))
print(X)
print('')
X -= 1
print(X)

[[10 12  3  4  5]
 [ 6  4  7  6  2]
 [ 6  1  7  5  9]
 [ 7  9  6 10  8]
 [ 3  1  2  8  5]]

[[ 9 11  2  3  4]
 [ 5  3  6  5  1]
 [ 5  0  6  4  8]
 [ 6  8  5  9  7]
 [ 2  0  1  7  4]]


In [ ]:
X=np.random.randint(0,100000,size=(5,5))
one = np.ones((5,5), dtype = np.int)
print(X, '\n', one, '\n', np.subtract(X, one))


[[31691 96953 98796 15590  5247]
 [60418 81663 38003 70471 23724]
 [82325 29835 52159 10393 69674]
 [ 4656 27977 36889 59107 82389]
 [83044 96729  4420 89437 79326]] 
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]] 
 [[31690 96952 98795 15589  5246]
 [60417 81662 38002 70470 23723]
 [82324 29834 52158 10392 69673]
 [ 4655 27976 36888 59106 82388]
 [83043 96728  4419 89436 79325]]


**Question 9** -  Create a 10x10 ndarray with the constant number 5.

In [ ]:
print(np.full((10, 10), 5))



[[5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]]


**Question 10** - Create an identity matrix of order 3.

In [ ]:
print(np.identity(3)) 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Question 11** - Create a vector containing 25 elements from a Normal Distribution.

In [ ]:
X = np.random.normal(size=(1,25))
print(X)

[[-0.74781933 -1.57423691 -1.06449582  0.58869212  1.25323608  0.8156458
  -0.2179162   0.11889354  0.37035992 -0.24905783  0.38426398  0.7841372
   1.68504436 -0.33596379  0.65392112  0.02360879  1.86750781 -0.99668512
  -0.82689013 -0.93586383  0.58349153  0.48168094 -1.29515847 -0.44064293
  -0.80119972]]


**Question 12** - Create a vector containing 20 numbers equally spaced from 0 to 1.

In [ ]:
X = np.linspace(0, 1, 20)
print(X)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


**Question 13** Given the matrix *`mat`*, you have to create a code to slice the matrix *`mat`* to create a submatrix that contains the 3rd,4th, and 5th rows and all columns, except the first column.

In [ ]:
mat = np.arange(1, 26).reshape(5, 5)
print(mat)
sub_mat = mat[2:, 1:]
print(sub_mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


**Question 14** - Given the matrix *`mat`*, which is the indexing of number 20?

In [ ]:
result = np.where(mat== 20)
print(result)

(array([3]), array([4]))


**Question 15** - Given the matrix *`mat`*, create a code that slices the first 3 rows of the 2nd column.

In [ ]:
sub_mat = mat[:3, 1]
print(sub_mat)

[ 2  7 12]


**Question 16** - Given the matrix *`mat`*, create a code that slices the matrix and shows just the last line.

In [ ]:
sub_mat = mat[-1, :]
print(sub_mat)

[21 22 23 24 25]


**Question 16** - Given the matrix *`mat`*, create a code that slices the matrix and shows the last 2 lines.

In [ ]:
sub_mat = mat[-2:, :]
print(sub_mat)

[[16 17 18 19 20]
 [21 22 23 24 25]]


**Question 17** - Compute the overall sum of *`mat`*.

In [ ]:
sum_mat = np.sum(mat)
print(sum_mat)

325


**Question 18** - Compute the overall standard devition of *`mat`*.

In [ ]:
sum_mat = np.std(mat)
print(sum_mat)

7.211102550927978


**Question 19** - Compute the sum of each column of *`mat`*.

In [ ]:
col_sum_mat = np.sum(mat, axis=0)
print(col_sum_mat)

[55 60 65 70 75]


**Question 20** - Compute the variance of each row of *`mat`*.

In [ ]:
var_sum_mat = np.var(mat, axis=1)
print(var_sum_mat)

[2. 2. 2. 2. 2.]


## **GREAT JOB!!!**